<a href="https://colab.research.google.com/github/Alexandre77777/computer_math/blob/main/2.%20%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0%20Numpy/%D0%91%D0%90%D0%97%D0%90_%D0%BF%D0%BE_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **БАЗА по NumPy**

Рассмотрим **основные свойства** и **возможности** массивов NumPy с примерами кода.

## **Основные свойства массивов**


In [ ]:
import numpy as np

a = [1,2,3]

a_np = np.array(a)
a_np.dtype

dtype('int64')

### **1. `dtype`**  
Каждый массив имеет атрибут `dtype`, который определяет тип данных его элементов (например, `int32`, `float64` и т.д.).

In [ ]:
import numpy as np

# Создаем массив с типом элементов int32
a = np.array([1, 2, 3], dtype=np.int32)
print("dtype:", a.dtype)  # Вывод: int32

dtype: int32


### **2. `shape`**  
Атрибут `shape` возвращает кортеж, определяющий размерность массива — количество элементов по каждой оси.

In [ ]:
import numpy as np

# Создаем двумерный массив
a = np.array([[1, 2, 3], [4, 5, 6]])
print("shape:", a.shape)  # Вывод: (2, 3)

shape: (2, 3)


### **3. `size`**  
Атрибут `size` показывает общее количество элементов в массиве.

In [ ]:
import numpy as np

# Трехстрочный массив
a = np.array([[1, 2], [3, 4], [5, 6]])
print("size:", a.size)  # Вывод: 6 (2*3)

size: 6


### **4. `ndim`**  
Атрибут `ndim` указывает на количество измерений массива.

In [ ]:
import numpy as np

# Пример одномерного массива
a = np.array([1, 2, 3])
print("ndim массива a:", a.ndim)  # Вывод: 1

# Пример двумерного массива
b = np.array([[1, 2], [3, 4]])
print("ndim массива b:", b.ndim)  # Вывод: 2

ndim массива a: 1
ndim массива b: 2




### **5. `itemsize`**  
Атрибут `itemsize` определяет, сколько байт занимает один элемент массива.

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
print("itemsize:", a.itemsize)  # Вывод: 4 (для int32 обычно 4 байта на элемент)

itemsize: 4



### **6. `strides`**  
Атрибут `strides` показывает количество байт, которое необходимо перескочить, чтобы перейти к следующему элементу по каждой оси, что полезно для понимания внутреннего расположения данных.

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("strides:", a.strides)
# Вывод может быть, например: (8, 4) — зависит от типа данных и платформы.

strides: (16, 8)


## **Основные возможности и полезные свойства массивов NumPy**

### **1. Векторизация операций**  
NumPy позволяет выполнять арифметические и логические операции над всеми элементами массива одновременно, что существенно ускоряет вычисления.

In [ ]:
b.shape

(3,)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print("Векторизация:", c)  # Вывод: [5 7 9]

Векторизация: [5 7 9]


### **2. Broadcasting**  
Механизм автоматического приведения массивов разной формы к совместимым размерам при выполнении арифметических операций.


In [ ]:
import numpy as np

# Пример простого broadcasting: умножение каждого элемента массива на скаляр
a = np.array([1, 2, 3])
b = 2
print("Broadcasting (умножение на скаляр):", a * b)

Broadcasting (умножение на скаляр): [2 4 6]


А также пример с разными размерами:


In [ ]:
import numpy as np

# Пример broadcasting для двумерного массива и одномерного вектора
a = np.array([[1], [2], [3]])  # Форма (3, 1)
b = np.array([10, 20, 30])       # Форма (3,)
print("Broadcasting (двумерная сумма):\n", a + b)

Broadcasting (двумерная сумма):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### **3. Продвинутые возможности индексации и срезов**  
Помимо стандартных срезов, доступны продвинутая (fancy) индексация и булевская индексация для выбора и фильтрации данных.

In [ ]:
a = ['cat', 'dog', 1, 23, 6]

[6, 23, 1, 'dog', 'cat']

In [ ]:
# Срезы
a = np.array([0, 1, 2, 3, 4, 5])
print("Срез:", a[2:5])  # Вывод: [2 3 4]

Срез: [2 3 4]


In [ ]:
# Булева индексация
b = np.array([10, 20, 30, 40])
mask = b > 20
print(mask)
print("Булева индексация:", b[mask])  # Вывод: [30 40]

[False False  True  True]
Булева индексация: [30 40]


In [ ]:
# Fancy индексация
indices = [0, 2]
print("Fancy индексация:", b[indices])  # Вывод: [10 30]

Fancy индексация: [10 30]


### **4. Методы для преобразования массива**  
Массивы можно преобразовывать, изменять их форму, "выпрямлять" в одномерный массив, или транпонировать.


- **reshape()**

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))
print("reshape:\n", b)

reshape:
 [[1 2 3]
 [4 5 6]]


- **flatten()**


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print("flatten:", b)

flatten: [1 2 3 4 5 6]


- **transpose()**

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.transpose(a)
print("transpose:\n", b)

transpose:
 [[1 4]
 [2 5]
 [3 6]]


### **5. Работа с копиями и представлениями**  
Методы `copy()` и `view()` позволяют создавать глубокие копии и неглубокие представления массива соответственно.

- **copy()**



In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 10
print("Оригинальный массив:", a)
print("Копия:", b)

Оригинальный массив: [1 2 3]
Копия: [10  2  3]



- **view()**


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = a.view()
b[0] = 10
print("Измененный оригинальный массив (view):", a)

Измененный оригинальный массив (view): [10  2  3]


### **6. Универсальные функции (ufuncs)**  
ufuncs — это оптимизированные функции для применения элементарных операций к массиву.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.sin(a)
print("Применение np.sin к массиву:", b)

Применение np.sin к массиву: [0.84147098 0.90929743 0.14112001]


### **7. Эффективное использование памяти и производительность**  
Благодаря компактному хранению однородных данных и оптимизированным операциям, массивы NumPy работают быстрее и используют память эффективнее, чем стандартные списки Python.

In [ ]:
import numpy as np
import time

# Создание большого массива
# a = np.arange(1000000)

# Пример быстрого умножения элементов массива на скаляр
start = time.time()
a = np.arange(10000000)
b = a * 2
end = time.time()
print("Время вычисления при векторизации:", end - start, "секунд")

Время вычисления при векторизации: 0.07938003540039062 секунд


array([       0,        2,        4, ..., 19999994, 19999996, 19999998])

In [ ]:
import numpy as np
import time

# Создание большого массива

# Пример быстрого умножения элементов массива на скаляр
start = time.time()
a = [int(i) for i in range(10000000)]
a = [i * 2 for i in a]
end = time.time()
print("Время вычисления при векторизации:", end - start, "секунд")

Время вычисления при векторизации: 2.1743059158325195 секунд
